[package]
name = "global"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["David J. Hamilton <david@hamilton.gg>"]

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.3", features = ["derive"] }
cargo_metadata = "0.18.1"
toml = "0.8.12"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
walkdir = "2.5.0"
config = { git = "https://github.com/malleatus/shared_binutils.git" }
latest_bin = { git = "https://github.com/malleatus/shared_binutils.git" }
regex = "1.10.6"
shellexpand = "3.1.0"

[dev-dependencies]
insta = { version = "1.36.1", features = ["yaml", "toml"] }
tempfile = "3.10.1"
temp-env = "0.3.6"
rand = "0.8.5"
test_utils = { git = "https://github.com/malleatus/shared_binutils.git" }
fixturify = { git = "https://github.com/malleatus/shared_binutils.git" }
