[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.3", features = ["derive"] }
latest_bin = { path = "../latest_bin" }
schemars = "0.8.21"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.122"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
mlua = { version = "0.9.7", features = ["lua54", "vendored", "serialize"] }

[dev-dependencies]
regex = "1.10.6"
insta = { version = "1.36.1" }
tempfile = "3.10.1"
test_utils = { path = "../test_utils" }
